# CircleCI 2.0 configuration file
version: 2
jobs:

  build:
    docker:
    - image: circleci/openjdk:8-jdk@sha256:150bc8d302f93a4895554c54a70394d460398548537eabde8f641e908101f90b
    steps:
    - checkout
    - restore_cache:
        key: gradle-{{ checksum "build.gradle" }}
    - run: ./gradlew clean build
    - save_cache:
        paths:
        - ~/.gradle
        key: gradle-{{ checksum "build.gradle" }}
    - persist_to_workspace:
        root: ./
        paths:
        - build
    - store_artifacts:
        path: build/libs
        destination: ./

  deploy:
    docker:
    - image: circleci/openjdk:8-jdk@sha256:150bc8d302f93a4895554c54a70394d460398548537eabde8f641e908101f90b
    steps:
    - checkout
    - restore_cache:
        key: gradle-{{ checksum "build.gradle" }}
    - attach_workspace:
        at: ./
    - run: echo -e $GRADLE_LOGIN > ~/.gradle/gradle.properties
    - run: ./gradlew publishPlugins
    - save_cache:
        paths:
        - ~/.gradle
        key: gradle-{{ checksum "build.gradle" }}

workflows:
  version: 2
  build-deploy:
    jobs:
    - build:
        filters:
          tags:
            only: /^\d+\.\d+\.\d+$/
    - deploy:
        requires:
          - build
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^\d+\.\d+\.\d+$/
